### ISSUE TITLE
CatsEffectSuite runs inner IO if it receives IO[IO[A]]

### ISSUE THREAD

**Issue by SystemFw** [typelevel/munit-cats-effect#159]
A colleague of mine spent hours fighting with Resource in a test due to a trivial mistake (`map` vs `flatMap`).
I've found out that CatsEffectSuite does something _really_ odd in this case however: it seems to run `unsafeToFuture` on both the outer _and_ inner `IO` when it receives `IO[IO[A]]`, maybe there is some implicit conversion happening.
The repro should make it clear:

```scala
import cats.effect._
import munit.CatsEffectSuite
import scala.concurrent.duration._

class Repro extends CatsEffectSuite {
  test("use after close") {
    Resource.make(IO.println("Open"))(_ => IO.println("Close")).use { _ =>
      IO.println("Enjoy: ").map { _ =>
        IO.sleep(1.second) >> IO.println("Use after close!")
      }
    }
  }

  test("minimised") {
    IO.println("Nope")
    IO.println("Hello").map { _ => IO.println("Surely not") }
  }
}

/*
sbt:root> testOnly *Repro*
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for Test / testOnly
Open
Enjoy: 
Close
Use after close!
Repro:
  + use after close 1.105s
Hello
Surely not
  + minimised 0.002s
[info] Passed: Total 2, Failed 0, Errors 0, Passed 2
[success] Total time: 1 s, completed 30 Nov 2021, 14:48:32
*/

```

**Comment by SystemFw** [comment]
After further conversation: the basic mechanism at play here is that munit applies value transforms recursively, which is useful: in cats-effect-munit we run a value transform from `IO` to `Future`, and then munit applies its own on the resulting Future, which results in the behaviour above when applied to `IO[IO[A]]`.
We cannot change that model as its fundamental to munit's design, but I'm going to leave this issue open for a bit to think of mitigation. Docs are the obvious one, but I'm thinking if there's any way we can detect `IO[IO[A]]` in `munit` cats-effect` specifically and fail. This is tricky because of the untyped nature of the munit api on one hand, and type erasure on the other, so it might be impossible altogether.

**Comment by olafurpg** [comment]
> it seems to run unsafeToFuture on both the outer and inner IO when it receives IO[IO[A]], maybe there is some implicit conversion happening.

I was made aware of this issue from an offline conversation with @gabro. MUnit automatically flattens futures, which is probably the culprit for this weird behavior

https://github.com/scalameta/munit/blob/dd5d392143c463d58c0d9ca06917169ec772d959/munit/shared/src/main/scala/munit/ValueTransforms.scala#L23-L24

There's even a test case that specifically stresses this code path for lazy futures

https://github.com/scalameta/munit/blob/dd5d392143c463d58c0d9ca06917169ec772d959/tests/shared/src/test/scala/munit/LazyFutureSuite.scala#L31-L38

I admit it's confusing to automatically flatten `IO` because they're lazy. This behavior was implemented with futures in mind that evaluate eagerly. I'm glad you were able to work around this quirk by failing the test at runtime https://github.com/typelevel/munit-cats-effect/pull/160
