### ISSUE TITLE
Lack of Cross-Platform Support for ResourceSuiteLocalFixture

### ISSUE THREAD

**Issue by ChristopherDavenport** [typelevel/munit-cats-effect#172]
For the same reason this is useful on the jvm, it would be useful when running for js.

Currently options are to have a build specific test and spin up resources on each test on js, or spin up resources on each test on both jvm and js, while ideally it would be nice to use this feature in cross-compatible code.

**Comment by armanbilge** [comment]
Try this: https://github.com/typelevel/munit-cats-effect/pull/104?

**Comment by armanbilge** [comment]
The underlying issue is that munit currently doesn't support async suite-local fixtures. The JVM implementation relies on blocking which we don't have on JS. The PR above introduces a workaround, however that is unsafe. This can be fixed after munit 1.0 is released, see https://github.com/typelevel/munit-cats-effect/issues/147.
